Redesign coaching popup
Bootstrap-Academy/frontend pull request #202
Opened 2024-05-05 11:43 UTC by Lauritz-Tieste

## Description
I redesigned the coaching popup on the calendar page.
![image](https://github.com/Bootstrap-Academy/frontend/assets/84938977/68d36a5d-c810-4de1-b6bf-c58b7c43d18d)

My Bootstrap Academy username: Lauritz

2024-05-08 15:34 UTC, Defelo requested changes
When trying to cancel a coaching (also seems to apply to webinars), the confirmation checkboxes are shown. These checkboxes should only be required when booking a coaching/webinar.

![image](https://github.com/Bootstrap-Academy/frontend/assets/41747605/61c5bc60-73d6-4901-a56c-92556a8b30b0)

2024-05-08 15:41 UTC, Lauritz-Tieste commented
When I try booking webinars, I always pay 10k morphcoins. Is there somehow a developer account for that

2024-05-08 16:14 UTC, Lauritz-Tieste commented
Ready.

2024-05-16 16:32 UTC, Defelo approved these changes

2024-05-16 16:32 UTC, merged