Add translations for image alt attributes
Bootstrap-Academy/frontend pull request #215
Opened 2024-05-23 20:39 UTC by Lauritz-Tieste

## Description
I have now included the previously hard-coded alt attributes in the translation files.

My Bootstrap Academy username: Lauritz

2024-05-23 20:51 UTC, Defelo requested changes

2024-05-23 20:51 UTC, Defelo commented on components/form/BuyCoins.vue
> +				:alt="t('AltAttributes.Morphcoins')"
The corresponding entries in locales/*.json seem to be missing

2024-05-23 20:51 UTC, Defelo commented on components/input/Media.vue
> -				:alt="alt"
Why has this been removed?

2024-05-23 20:51 UTC, Defelo commented on components/skill-tree/Progress.vue
> +        :alt="t('AltAttributes.SkillCover')"
The corresponding entries in locales/*.json seem to be missing

2024-05-24 07:47 UTC, Lauritz-Tieste commented on components/input/Media.vue
> -				:alt="alt"
by accident

2024-05-24 14:09 UTC, Defelo approved these changes

2024-05-24 14:09 UTC, merged