Add limit to 256 characters when creating a quiz
Bootstrap-Academy/frontend pull request #221
Opened 2024-05-26 14:23 UTC by Lauritz-Tieste

## Description
I added a limit to 256 characters when creating a quiz, because the backend cannot handle more.

fixes https://github.com/Bootstrap-Academy/Bootstrap-Academy/issues/75

My Bootstrap Academy username: Lauritz

2024-05-26 22:34 UTC, Defelo requested changes
The length of the question should also be checked

2024-05-26 22:34 UTC, Defelo commented on components/form/Quiz.vue
> +            return openSnackbar("error", "Error.OptionCannotBeMoreThen256");
```suggestion
            return openSnackbar("error", "Error.OptionCannotBeMoreThan256");
```

Also the translation key seems to be missing

2024-05-28 08:41 UTC, Lauritz-Tieste reviewed
After all the back and forth with the commits, it should work now

2024-05-28 14:13 UTC, Defelo requested changes

2024-05-28 14:13 UTC, Defelo commented on components/form/Quiz.vue
> +        }
The maximum length of the question is actually 4096, see https://api.test.bootstrap.academy/challenges/redoc#tag/MultipleChoice/paths/~1tasks~1%7Btask_id%7D~1multiple_choice/post

```suggestion
        if (form.question.value.length > 4096) {
          return openSnackbar("error", t("Error.CannotHaveMoreCharacters", { input: t("Inputs.Question"), max: 4096 }));
        }
```

2024-05-28 14:13 UTC, Defelo commented on components/form/Quiz.vue
> +          if (options.value[i].answer.length > 255) {
Why 255? The maximum length of each option is 256 (inclusive), so 256 characters are still allowed.
```suggestion
          if (options.value[i].answer.length > 256) {
```

2024-05-28 14:25 UTC, Defelo approved these changes

2024-05-28 14:25 UTC, merged