Refactoring across the repo
Bootstrap-Academy/frontend pull request #33
Opened 2023-10-08 16:21 UTC by SpotlightForBugs

## Description

## Type of change
Refactored two things:
- refactor: convert logical operator to optional chaining
> The [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) operator can be used to perform null checks before accessing a property, or calling a function.
- refactor: remove unnecessary boolean casts
> In contexts such as an if statement's test where the result of the expression will already be coerced to a Boolean, casting to a Boolean via double negation (!!) or a Boolean call is unnecessary.

My Bootstrap Academy username: SFB

2023-10-08 16:36 UTC, SpotlightForBugs reviewed
I think that these changes help more people to start contributing because they don’t have to deal with `!!!` or `!!` anymore

2023-10-09 11:11 UTC, Joshiy13 approved these changes

2023-10-09 14:50 UTC, SpotlightForBugs commented
@Joshiy13 i resolved conflicts, okay?

2023-10-10 17:03 UTC, SpotlightForBugs commented
@Defelo was denkst du? (Kein Bock immer Konflikte zu beheben)
---
@Defelo what do you think? (I don’t feel like always resolving conflicts)

2023-10-11 16:26 UTC, Defelo requested changes
There are lots of unneeded parentheses now, mostly where double negation was removed, this should be fixed before merging.

2023-10-11 16:26 UTC, Defelo commented on components/form/Webinar.vue
>  				if (!!!time.value || time.value == '00:00:00') isValid = false;
What about this one?

2023-10-11 16:26 UTC, Defelo commented on components/hero/FAQS.vue
> +				}
This was fixed in a previous pr, why did you change this back?

2023-10-11 16:26 UTC, Defelo commented on components/Chip.vue
> +      return (props.color)
1. These parentheses are useless.
2. I think, you can use the `??` operator here.

2023-10-30 10:41 UTC, Defelo commented
Hi @SpotlightForBugs, are you still working on this?

2023-10-30 12:30 UTC, SpotlightForBugs commented
@Defelo yes, I am

2025-08-23 10:44 UTC, closed without merging