Translation and overall language improvements
Bootstrap-Academy/frontend pull request #34
Opened 2023-10-08 17:38 UTC by Joshiy13

## Description
This PR tries to make the translation and overall wording better.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Translation updates (fix/improve or add new translations)

My Bootstrap Academy username: Joshiy13

2023-10-09 09:35 UTC, Joshiy13 commented
Also fixes [#54](https://github.com/Bootstrap-Academy/Bootstrap-Academy/issues/54)

2023-10-11 09:37 UTC, Joshiy13 commented
@Defelo Could you review this?

2023-10-11 16:08 UTC, Defelo requested changes

2023-10-11 16:08 UTC, Defelo commented on locales/de.json
> +    "HeroFAQS": "FAQs",
I think "FAQ" is already correct since the "Q" already stands for "question**s**"

2023-10-11 16:08 UTC, Defelo commented on locales/en-US.json
> +      "Body": "You have not watched courses yet. Explore the skill tree to get started."
```suggestion
      "Body": "You have not watched any courses yet. Explore the skill tree to get started."
```

2023-10-11 16:15 UTC, josiebytes commented on locales/de.json
> +    "HeroFAQS": "FAQs",
Yeah that makes sense

2023-10-11 16:31 UTC, Defelo approved these changes

2023-10-11 16:31 UTC, merged